"""2

Revision ID: 617b4526dc20
Revises: f47de972cd49
Create Date: 2025-06-04 14:34:58.226566

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '617b4526dc20'
down_revision: Union[str, None] = 'f47de972cd49'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('node',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('prev_node', sa.Integer(), nullable=True),
    sa.Column('pair', sa.Integer(), nullable=False),
    sa.Column('left_node', sa.Integer(), nullable=True),
    sa.Column('right_node', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['left_node'], ['node.id'], ),
    sa.ForeignKeyConstraint(['pair'], ['pair.id'], ),
    sa.ForeignKeyConstraint(['prev_node'], ['node.id'], ),
    sa.ForeignKeyConstraint(['right_node'], ['node.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pair',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('left_team_id', sa.Integer(), nullable=False),
    sa.Column('right_team_id', sa.Integer(), nullable=False),
    sa.Column('parent_node', sa.Integer(), nullable=False),
    sa.Column('_winner', sa.Enum('LEFT', 'RIGHT', 'NONE', name='winnerside'), nullable=False),
    sa.ForeignKeyConstraint(['left_team_id'], ['team.id'], ),
    sa.ForeignKeyConstraint(['parent_node'], ['node.id'], ),
    sa.ForeignKeyConstraint(['right_team_id'], ['team.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('team',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), server_default=sa.text("'---'"), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tournament',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), server_default=sa.text("'---'"), nullable=True),
    sa.Column('root_node', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['root_node'], ['node.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tournament')
    op.drop_table('team')
    op.drop_table('pair')
    op.drop_table('node')
    # ### end Alembic commands ###
